language: python
  
python: "3.7.4"
  
# don't clone more than necessary
git:
  depth: 1
  
# script to run tests. Script can have many commands, one per line.
script: 
  - python -m unittest discover -p "*_test.py"
  - py.test  --cov-report term --cov=app/test/

env:
  - CODECOV_TOKEN=dbe0b739-5ff0-48a0-a8ae-b8c8b6bfe3fe

after_success:
  - codecov